#配置数据源
spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/smbms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
#  静态资源
  resources:
    static-locations: classpath:templates/,classpath:/static/
#设置端口号
server:
  port: 80
#mybatis配置
mybatis:
  type-aliases-package: com.hz.springbootday01.entity
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印SQL语句
#    cache-enabled: true



